version: '3' # composeファイルのバーション指定
services:
  app: # service名
    container_name: go
    build:
      context: . # どこをカレントディレクトリとしてみるかということ。Dockerfileの中のパスの書き方も変わるから注意
      dockerfile: ./docker/Dockerfile # ビルドに使用するDockerfileがあるディレクトリ指定
    tty: true # コンテナの起動永続化
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/atcoder # マウントディレクトリ指定
