"""create user_name

Revision ID: 3d2532c5c114
Revises: d563dc996164
Create Date: 2021-01-03 16:08:34.804509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d2532c5c114'
down_revision = 'd563dc996164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('user_name', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'session', ['user_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='unique')
    op.drop_column('session', 'user_name')
    # ### end Alembic commands ###
