"""create user, post

Revision ID: 8868c8517cf8
Revises: 88d513a1ff85
Create Date: 2020-12-26 15:38:57.830609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8868c8517cf8'
down_revision = '88d513a1ff85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
