"""delete unique

Revision ID: a8e5fba33c8d
Revises: 3d2532c5c114
Create Date: 2021-01-06 02:16:32.735108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e5fba33c8d'
down_revision = '3d2532c5c114'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('session_email_key', 'session', type_='unique')
    op.drop_constraint('session_user_name_key', 'session', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('session_user_name_key', 'session', ['user_name'])
    op.create_unique_constraint('session_email_key', 'session', ['email'])
    # ### end Alembic commands ###
