"""add usersession

Revision ID: b236807abce5
Revises: a448eed284c2
Create Date: 2020-12-26 17:44:17.169182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b236807abce5'
down_revision = 'a448eed284c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
